import json
import re
from pathlib import Path

import pytest

from web.management.commands.export_static import (
    canonical_url, output_path, public_href, should_crawl,
)
from scripts.publish_pages import validate_internal_links


def test_canonical_url_sorts_queries_and_rejects_external_links():
    assert canonical_url("?thr=90&day=today", "/") == "/?day=today&thr=90"
    assert canonical_url("https://example.com/") is None
    assert canonical_url("/static/app.css") is None
    assert canonical_url("?season=2025&amp;week=8", "/nfl/") == "/nfl/?season=2025&week=8"


def test_primary_export_paths_are_readable():
    assert output_path("/") == Path("index.html")
    assert output_path("/?day=tomorrow") == Path("tomorrow/index.html")
    assert output_path("/nfl/") == Path("nfl/index.html")
    query_path = output_path("/results/?date=2026-08-14")
    assert query_path.parts[:1] == ("view",)
    assert public_href(query_path) == f"/{query_path.parent.as_posix()}/"


def test_crawler_keeps_bounded_performance_controls_and_excludes_nfl_archive():
    assert should_crawl("/performance/?period=30&market=hits&direction=over")
    assert not should_crawl("/performance/?period=30&league=MLB")
    assert not should_crawl("/performance/?period=30&league=MLB&market=hits")
    assert should_crawl("/results/?date=2026-08-14")
    assert not should_crawl("/results/?date=2026-08-14&league=MLB")
    assert not should_crawl("/nfl/?season=2025&week=4")
    assert not should_crawl("/nfl/")
    assert should_crawl("/game/MLB/401/")
    assert should_crawl("/game/MLB/401/?day=today")
    assert should_crawl("/?day=today&league=MLB")


def test_public_assets_are_not_cached_immutably():
    source = Path("web/management/commands/export_static.py").read_text()
    assert "max-age=300, must-revalidate" in source
    assert "max-age=31536000, immutable" not in source


def test_live_score_script_normalizes_espn_states_and_hides_completed_games():
    source = Path("web/static/static-site.js").read_text()
    assert 'sourceState === "in" ? "live"' in source
    assert 'sourceState === "post" ? "final"' in source
    assert "data-toggle-completed" in Path("web/templates/web/today.html").read_text()
    assert "applyCompletedVisibility" in source


def test_static_link_audit_rejects_server_query_links(tmp_path):
    (tmp_path / "index.html").write_text(
        '<a href="/performance/?market=hits">Broken static filter</a>'
    )
    try:
        validate_internal_links(tmp_path)
    except RuntimeError as exc:
        assert "query URL" in str(exc)
    else:
        raise AssertionError("query-only application links must fail the static audit")


# --- standards compliance (2026-08-17) ---------------------------------------------

# These read the checked-in export rather than rebuilding into a temp directory: the
# export command deliberately refuses to write outside the project (a path-traversal
# guard), and weakening that for a test would be the wrong trade. `site-dist/` is
# regenerated by every publish, so it is the artefact worth asserting on.
_DIST = Path(__file__).resolve().parents[2] / "site-dist"

pytestmark = pytest.mark.skipif(
    not (_DIST / "index.html").exists(),
    reason="site-dist/ not built — run `python -m scripts.publish_pages --build-only`",
)


def _index() -> str:
    return (_DIST / "index.html").read_text()


def test_the_slate_page_states_its_subject_in_exactly_one_h1():
    """The page had no <h1> at all — its only heading was <h2>Top Opportunities and the
    site name lived in a <footer>, so it announced no subject to a screen reader and no
    topic to a search engine. Exactly one, because two competing <h1>s is its own defect.
    """
    headings = re.findall(r"<h1[^>]*>(.*?)</h1>", _index(), re.S)
    assert len(headings) == 1, f"expected one <h1>, found {len(headings)}"
    assert headings[0].strip(), "the <h1> must not be empty"


def test_template_comments_do_not_leak_into_the_page():
    """Django's `{# #}` is single-line only. Written as a multi-line block, the
    continuation lines render as page text — which is how an explanatory comment about
    the <h1> ended up *inside* the <h1> on the first attempt."""
    html = _index()
    for phrase in ("screen reader met", "search engines saw", "Visually hidden because"):
        assert phrase not in html, f"template comment leaked into the page: {phrase!r}"


def test_the_page_carries_mobile_web_app_metadata():
    """This is read on a phone from the home screen. Without these the icon falls back to
    a screenshot, the status bar ignores the dark canvas, and launching shows browser
    chrome instead of running full-screen."""
    html = _index()
    for tag in ('name="theme-color"', 'rel="apple-touch-icon"',
                'name="apple-mobile-web-app-capable"', 'rel="manifest"'):
        assert tag in html, f"missing {tag}"


def test_a_keyboard_user_can_skip_the_navigation():
    """The nav renders before the slate, so without this a keyboard or switch user tabs
    through every filter pill and league toggle before reaching the first game."""
    html = _index()
    assert 'class="skip-link"' in html
    # The export canonicalises internal hrefs, so the skip link ships as "/#main" rather
    # than the bare "#main" written in the template. Match the fragment, not the form.
    assert re.search(r'class="skip-link"[^>]*href="[^"]*#main"', html)
    assert 'id="main"' in html, "the skip link needs a target"


def test_reduced_motion_is_respected():
    """The stylesheet animates a live-game dot and transitions several controls; none of
    it carries meaning that is lost when stilled."""
    css = (_DIST / "static" / "web.css").read_text()
    assert "prefers-reduced-motion" in css


def test_the_manifest_is_valid_and_launches_standalone():
    """`display: standalone` is what actually drops browser chrome; without it the rest
    of the metadata is decorative."""
    manifest = json.loads((_DIST / "static" / "site.webmanifest").read_text())
    assert manifest["display"] == "standalone"
    assert manifest["icons"], "a manifest with no icons gives the home screen nothing"
    for icon in manifest["icons"]:
        assert (_DIST / icon["src"].lstrip("/")).exists(), f"missing {icon['src']}"
